### ISSUE TITLE
Pre-trained model link

### ISSUE THREAD

**Issue by suhwan-cho** [NUST-Machine-Intelligence-Laboratory/HFAN#15]
Hi, thanks for your interesting work!

I tried to download the pre-trained models, but I cannot use Baidu.

Could you please provide the models on Google Drive for people like me?

Thank you!

**Comment by PGSmall** [comment]
Thanks for your attention. I provided a [OneDrive link](https://njusteducn-my.sharepoint.com/:f:/g/personal/peigsh_njust_edu_cn/ErQg7myZHCZDnEGsIi-EWDoBIt0U1MtSeMmGE868stXwrQ).

**Comment by suhwan-cho** [comment]
Thanks a lot!
