### ISSUE TITLE
YouTubeVOS Dataset

### ISSUE THREAD

**Issue by sutiankang** [NUST-Machine-Intelligence-Laboratory/HFAN#2]
Hello, Thanks for sharing your great work. Could you send me the YouTubeVOS dataset in the form of Baidu Pan, because Google Drive always breaks when I download the dataset.

**Comment by Study4IM** [comment]
Thanks for your attention!

YouTubeVOS and DAVIS have already been uploaded to [BaiduDrive](https://pan.baidu.com/s/11aU4KLo6GMsUfIGppaFC3g?pwd=2n4u).

**Comment by CODE4UVOS** [comment]
Thanks for your attention!

YouTubeVOS and DAVIS have already been uploaded to [BaiduDrive](https://pan.baidu.com/s/11aU4KLo6GMsUfIGppaFC3g?pwd=2n4u).

**Comment by sutiankang** [comment]
@CODE4UVOS Thanks.
