### ISSUE TITLE
OMP_NUM_THREADS

### ISSUE THREAD

**Issue by chengguanjun** [NUST-Machine-Intelligence-Laboratory/HFAN#3]
Hello, Thanks for sharing your great work.However, I still don't understand how to set the parameter "OMP_NUM_THREADS". Does this parameter affect the final performance?Hope for your reply.

**Comment by CODE4UVOS** [comment]
Thanks for your attention!

`OMP_NUM_THREADS` sets the number of threads to use during execution, which has no impact on performance. It needs to be set the appropriate number when the training model uses more than one GPU. 

Just set `OMP_NUM_THREADS` to the number of available CPUs.

![image](https://user-images.githubusercontent.com/94226886/183425417-fb12215d-ce14-4e07-80de-8e16110713db.png)

**Comment by cgj4992008** [comment]
@CODE4UVOS Ok, thank you very much!
