### ISSUE TITLE
Long-Videos dataset and VSOD

### ISSUE THREAD

**Issue by chengguanjun** [NUST-Machine-Intelligence-Laboratory/HFAN#8]
Hello, Thanks for sharing your great work.Could you please provide the processed long-video dataset?Also, for the VSOD task, how should I modify the code to get the gray level segmentation results?Hope for your reply.

**Comment by CODE4UVOS** [comment]
Thanks for your attention.
1. For the Long-Videos dataset, you can find it [here](https://www.kaggle.com/gvclsu/long-videos).
2. For the VSOD task, the results obtained by HFAN are binarized masks [0,255].

**Comment by chengguanjun** [comment]
@CODE4UVOS Ok, thank you very much!
